[style]
    primary = "#006b60"

[main]

    description = "A collection of resources and insights to help you deploy passkeys, including practical user experiences, device ecosystem support, frequently asked questions, and more."
    images = ["/img/share-cover.png"]

[main.externalLinks]
    cue = false
    tab = true

[navigation]
    logo = "/img/logos/pdd-logo-color-nopad-light.svg"
    title = "passkeys.dev"
    breadcrumb = false
    toc = true
    sidebar = true
    fixed = true

[footer]
    license = '<a href="about/#copyright-and-attributions">CC BY-NC-ND 4.0</a>'
    description = 'This site is brought to you by members of the <a href="https://www.w3.org/community/webauthn-adoption/" target="_blank">W3C WebAuthn Community Adoption Group</a> and the <a href="https://fidoalliance.org/" target="_blank">FIDO Alliance.</a>'

[favicon]
    logo = "img/favicon.png"
    sizes = [16, 32, 48]


[schema]
    type = "Organization"
    name = "passkeys.dev"
    locale = "en-US"
    github = "https://github.com/passkeydeveloper/passkeys.dev"
    [logo]
        url = "/img/share-cover.png"
        width = 1280
        height = 640
    [image]
        url = "/img/share-cover.png"
        width = 1280
        height = 640

[opengraph]
    images = ["/img/logo.png"]
    locale = "en_US"

[docs]
    github = "https://github.com/passkeydeveloper/passkeys.dev"

[sharing]
    enabled = true
    sort = "weight"
    reverse = false
    webshare = true

[[sharing.providers]]
    name = "link"
    url = "{url}"
    icon = "fas link"
    weight = 10
    clipboard = true

[[sharing.providers]]
    name = "Bluesky"
    url = "https://bsky.app/intent/compose?text={url}"
    icon = "fab bluesky"
    weight = 20

[[sharing.providers]]
    name = "Mastodon"
    url = "https://s2f.kytta.dev/?text={url}"
    icon = "fab mastodon"
    weight = 30

[[sharing.providers]]
    name = "LinkedIn"
    url = "https://www.linkedin.com/sharing/share-offsite/?url={url}"
    icon = "fab linkedin"
    weight = 40

[[sharing.providers]]
    name = "Threads"
    url = "https://www.threads.net/intent/post?text={url}"
    icon = "fab threads"
    weight = 50

[[sharing.providers]]
    name = "WhatsApp"
    url = "whatsapp://send?text={title}%20{url}"
    icon = "fab whatsapp"
    weight = 60
