
[[main]]
  name = "Docs"
  pageRef = "/docs/"
  weight = 10

[[main]]
  name = "Device Support"
  pageRef = "/device-support/"
  weight = 20

[[main]]
  name = "Tools"
  pageRef = "https://tools.passkeys.dev"
  weight = 25

[[main]]
  name = "About"
  pageRef = "/about/"
  weight = 30

[[main]]
  name = "Discussions"
  pre = "fa fa-comments"
  url = "https://passkeys.dev/discuss"
  weight = 110
  [main.params]
    icon = true


[[main]]
  name = "GitHub"
  pre = "fab fa-github"
  url = "https://github.com/passkeydeveloper"
  weight = 120
  [main.params]
    icon = true

[[main]]
  name = "Bluesky"
  pre = "fab fa-bluesky"
  url = "https://bsky.app/profile/passkeys.dev"
  weight = 140
  [main.params]
    icon = true

[[main]]
  name = "Mastodon"
  pre = "fab fa-mastodon"
  url = "https://fosstodon.org/@passkeysdev"
  weight = 140
  [main.params]
    icon = true

[[footer]]
  name = "Links"
  weight = 10

[[footer]]
  parent = "Links"
  name = "Docs"
  pageRef = "/docs/"
  weight = 10

[[footer]]
  parent = "Links"
  name = "About"
  pageRef = "/about/"
  weight = 20

[[footer]]
  parent = "Links"
  name = "Device Support"
  pageRef = "/device-support/"
  weight = 30

[[footer]]
  name = "Resources"
  weight = 20

[[footer]]
  parent = "Resources"
  name = "Passkey Central"
  url = "https://passkeycentral.org"
  weight = 10

[[footer]]
  parent = "Resources"
  name = "Dev Discussions"
  pageRef = "https://passkeys.dev/discuss"
  weight = 20

[[footer]]
  parent = "Resources"
  name = "FIDO Alliance"
  pageRef = "https://fidoalliance.org"
  weight = 30

[[footer]]
  name = "Tools"
  weight = 30

[[footer]]
  parent = "Tools"
  name = "Passkey Developer Tools"
  url = "https://tools.passkeys.dev"
  weight = 10

[[footer]]
  parent = "Tools"
  name = "WebAuthn Response Decoder"
  url = "https://debugger.simplewebauthn.dev/"
  weight = 20
